baseurl = "http://www.quicheanon.com/"
languageCode = "en-us"
title = "Quiche-Anon"
theme = "castanet"
googleAnalytics = "UA-182123125-1"
paginate = "9"


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

# [[Menu.Main]]
#     name = "Contact"
#     identifier = "contact"
#     url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[params]
mainSections = ["episode"]
site_theme = "grey"
# site_layout = "grid"
site_layout = "row"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
favicon = "favicon.ico"
about_logo = "/img/quiche-anon-logo-500.jpg"
copyright_notice = "Copyright 2020 [Quiche-Anon](https://www.quicheanon.com)"
# itunes_subscribe = "https://podcasts.apple.com/us/podcast/arrested-devops/id773888088?ign-mpt=uo%3D4&mt=2"
android_subscribe = "https://www.subscribeonandroid.com/feeds.blubrry.com/feeds/quicheanon.xml"
# spotify_subscribe = "https://open.spotify.com/show/..."
# google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
# stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
# soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
pocketcasts_subscribe = "http://pca.st/459nu3mz"
# mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "A podcast about conspiracy theories and cooking. Hosts Kelli and Matt will take you on a journey through the deepest, darkest paths of conspiracy theories - mixed in with their takes on what makes food amazing and delicious."
media_prefix = "https://media.blubrry.com/arresteddevops/content.blubrry.com/quicheanon/"
disqusShortname = ""
  [params.feed]
    copyright = "Copyright 2020 Quiche-Anon" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "A podcast about conspiracy theories and cooking" #no markdown or HTML
    itunes_author = "Kelli Prichard and Matt Stratton" #no markdown or HTML
    itunes_summary = "Hosts Kelli and Matt talk about their favorite conspiracy theories, as well as favorite recipes and cooking tips. A delightful mix of conspiracy and cooking." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Matt Stratton"
    itunes_owner_email = "matt.stratton@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "https://www.quicheanon.com/img/quiche-anon-logo-big.jpg" #fqdn to the image art for your podcast
    itunes_top_category = "News"
    itunes_first_sub_category = "News Commentary"
    # itunes_second_sub_category = "Tech News"
    language = "en-us"
    explicit = "yes"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

#   [params.podlove] # https://subscribe-button.podlove.org
#     subscribe_title = ""              # fallback: site title from above
#     subscribe_subtitle = ""           # fallback: ""
#     subscribe_description = ""        # fallback: ""
#     subscribe_cover = "/img/quiche-anon-logo-500.jpg"  # fallback: ""
#     subscribe_color = "#585e6c"       # fallback: ""
#     subscribe_size = "medium"         # options: small, medium, big
#     subscribe_format = "rectangle"    # options: rectangle, square, cover
#     subscribe_style = "filled"        # options: filled, outline, frameless
#     subscribe_language = "en"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
#     subscribe_feed_type = "audio"     # options: audio, video
#     subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    twitter = "quicheanon"
    twitter_domain = "quicheanon.com" # This domain shows in twitter cards as "View on `twitter_domain`"

  [params.authors]
    [params.authors.Matt]
      name	= "Matt Stratton"
      thumbnail = "img/host/matt.jpg"
      bio = "Matt Stratton is a solutions architect at Chef, where he demonstrates how Chef’s automation platform provides speed and flexibility to clients’ infrastructure. He is devoted to concepts like Continuous Delivery and Infrastructure as Code, and his license plate actually says “DevOps”. He lives in Chicago and has an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And whiskey."
      [params.authors.Matt.social]
        github = "mattstratton"
        twitter = "mattstratton"
        linkedin = "mattstratton"
        homepage = "https://www.mattstratton.com"
        instagram = "instagram"
        twitch = "mattstratton"
    [params.authors.Kelli]
        name = "Kelli Prichard"
        thumbnail = "img/host/kelli.jpg"
        twitter = "allaboutkelli"
